name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Find and Grant execute permission for gradlew
        run: |
          GRADLEW_PATH=$(find . -name gradlew)
          echo "Found gradlew at: $GRADLEW_PATH"
          chmod +x $GRADLEW_PATH
          echo "BASE_DIR=$(dirname $GRADLEW_PATH)" >> $GITHUB_ENV

      - name: Build Debug APK
        run: |
          cd ${{ env.BASE_DIR }}
          ./gradlew assembleDebug

      - name: Find and Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ThanyaOnline-Debug-APK
          path: "**/build/outputs/apk/debug/app-debug.apk"
